config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :edit, :update, :show] do
    get "/change_password" => "users#change_password"
  end

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
    get :forgot_password, on: :collection
  end

  resources :auctions do
    resources :bids, only: [:create]
    resources :publishings, only: [:create]

  end

  resources :bids, only: [:index]

  root "auctions#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    can :manage, Auction, user_id: user.id
    
    can :create, Bid
    cannot :create, Bid, auction: {user: user}

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  include AASM

  aasm whiny_transitions: false do
  state :draft, initial: true
  state :published
  state :cancelled
  state :won
  state :reserve_not_met
  state :reserve_met

  event :publish do
    transitions from: :draft, to: :published
  end

  event :win do
    transitions from: :published, to: :won
  end

  event :cancel do
    transitions from: [:draft, :published, :won], to: :cancelled
  end

  event :meet_reserve do
    transitions from: :published, to: :reserve_met
  end
end

belongs_to :user
has_many :bids

validates :end_date, presence: true
validates :reserve_price, presence: true
validates :title, presence: true

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user

  validates :amount, presence: true, numericality: {greater_than: :auction_current}
  validates :user_id, presence: true

  def auction_current
    auction.current_price
  end

  def auction_title
    auction.title
  end

  def user_full_name
    user.full_name
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy

  validates :password, length: {minimum: 6}, on: :create
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
            on: :create

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def sign_in(user)
    session[:user_id] = user.id
  end

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in." unless user_signed_in?
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

  def new
    @auction = Auction.new
  end

  def create
    auction_params = params.require(:auction).permit(:title, :details, :end_date, :reserve_price)
    @auction = Auction.new(auction_params)
      @auction.user = current_user
      if @auction.save
        redirect_to @auction, notice: "Auction created!"
      else
        flash[:alert] = "Auction not created! Please see errors below."
        render :new
      end
  end

  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new(auction: @auction)
    @bids = @auction.bids
    
  end

  def index
    @auctions = Auction.all
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    bid_params = params.require(:bid).permit(:amount)
    @bid = Bid.new bid_params
    @auction = Auction.find(params[:auction_id])
    @bid.auction = @auction
    @bid.user = current_user
    if @bid.save
        @auction.current_price = @bid.amount
        @auction.save
        redirect_to @auction, notice: "Bid submitted!"
    else
        flash[:alert] = "Bid not created"
                      redirect_to @auction
    end
  end


  def index
    @bids = current_user.bids
  end

end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController

  before_action :authenticate_user

  def create
    auction = Auction.find params[:auction_id]
    if auction.publish!
      redirect_to auction, notice: 'Auction Published'
    else
      redirect_to auction, alert: 'Can\'t publish the auction'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Try again"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation))
      if @user.save
        sign_in(@user)
        redirect_to root_path, notice: "Account created"
      else
        flash[:alert] = "Something went wrong"
        render :new
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_form.html.erb
<%= simple_form_for @auction do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :end_date, as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :reserve_price, as: :string %>
  <%= f.submit %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('input.datepicker').data({behaviour: "datepicker"}).datepicker({ format: 'yyyy-mm-dd' });
  });
</script>

app/views/auctions/index.html.erb
<h1>Auctions Index</h1>

<% @auctions.each do |auction| %>
<div class="">
  <h3><%= link_to auction.title, auction %></h3>

</div>
<% end %>

app/views/auctions/new.html.erb
<h1>Create Auction</h1>

<%= render 'form' %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>

<p><%= @auction.details %></p>
<br>
<% if can? :manage, @auction %>
<% end %>
<p>End Date: <%= @auction.end_date %></p>
<p>Reserve Price: <%= @auction.reserve_price %></p>
<p>Current Price: <%= @auction.current_price %></p>
<% if @auction.current_price < @auction.reserve_price %>
  <p>
    Reserve not met
  </p>
  <% else %>
  <p>
    Reserve has been met
  </p>
<% end %>

<div>
      <h2>Bids:</h2>
      <% if @bids.any? %>
          <div>
          <% @bids.each do |bid| %>
            <p><%= number_to_currency(bid.amount) %> on <%= bid.created_at.strftime("%D")%> by <%= bid.user_full_name %></p>
          <% end %>
          </div>
        <% else %>
          <p>No bids yet!</p>
        <% end %>

</div>

<% if can? :manage, @auction %>
  <% if @auction.draft? %>
   <p>Auction is draft<p>
       <%= link_to 'Publish', auction_publishings_path(@auction), method: :post, data: {confirm: 'Are you sure'}%>
   <% elsif @auction.published? %>
     <p>Auction is published<p>

  <% end %>
<% end %>

<% if user_signed_in? %>
  <% if can? :create, @bid %>
  <div>
  <h2>Create Bid: </h2>
    <div>
      <%= simple_form_for [@auction, @bid] do |f| %>
        <%= f.input :amount, as: :string %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/bids/index.html.erb
<h1>Your Bids</h1>
<% @bids.each do |bid| %>
  <div class="">
    <h3><%= number_to_currency(bid.amount) %> on <%= bid.auction_title %> at <%= bid.created_at.strftime("%D") %></h3>
    <p>Current Auction Price for <%= bid.auction_title %>: <%= number_to_currency(bid.auction_current) %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biddr</title>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <nav class="navbar navbar-default"> -->
      <div class="container-fluid">
        <div class="col-sm-12">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "New Auction", new_auction_path %></li>
              <li><%= link_to "All Auctions", auctions_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to "My Bids", bids_path %></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Welcome #{current_user.first_name} #{current_user.last_name}!"%></li>
                <li><%= link_to "Log Out", sessions_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign In", new_session_path %></li>
                <li><button class="btn btn-default navbar-btn"><%= link_to "Sign Up", new_user_path %></button></li>
              <% end %>
            </ul>
          <!-- </div> -->
        <!-- </div> -->
      </div>
    </nav>

    <div class="">
  <%= alert || notice %>
</div>

<%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= simple_form_for @user, defaults: {input_html: {class: 'form-vertical' } } do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <% if user_signed_in?%>
    <%= f.input :current_password %>
  <% else %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>